/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  pair_code_id: number;
}
export type ExecuteMsg = {
  create_new_pair: {
    asset_infos: [TokenInfo, TokenInfo];
  };
};
export type TokenInfo = {
  c_w20_token: {
    contract_addr: Addr;
  };
} | {
  native_token: {
    denom: string;
  };
};
export type Addr = string;
export type QueryMsg = {
  pair: {
    asset_infos: [TokenInfo, TokenInfo];
  };
} | {
  get_owner: {};
};
export interface PoolInfo {
  assets: [TokenInfo, TokenInfo];
  pair_addr: string;
}